
<script src="/js/j-3.js"></script>
<script src="/js/j-ui.js"></script>
<script src="/js/bt.js"></script>
{{-- <script src="{{ mix('js/app.js') }}"></script> --}}
<script src="/js/mdesign.js"></script>
<script src="/js/score.js"></script>
<script src="/js/jquery.validate.min.js"></script>
<script src="/js/moment.js"></script>
<script src="/js/chart.js"></script>
<script src="/js/jbt.js"></script>
<script src="/js/jn.js"></script>
<script src="/js/js.js"></script>
<script src="/js/jd.js"></script>
<script src="/js/jj.js"></script>
<script src="/js/nou.js"></script>
<script src="/js/gmap.js"></script>
<script src="/js/jselect.js"></script>
<script src="/js/jdata.js"></script>
<script src="/js/js2.js"></script>
<script src="/js/jasny.js"></script>
<script src="/js/fullc.js"></script>
<script src="/js/jt.js"></script>
<script src="/js/mdashboard.js"></script>
<script src="/js/demo.js"></script>
